using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public enum Wwise_ID_Enum 
{
    NONE = 0,
    NIVEAU_OX_5 = (int)AK.EVENTS.PLAY_NIVEAU_OX_5 ,
    NIVEAU_OX_10 = (int)AK.EVENTS.PLAY_NIVEAU_OX_10 ,
    NIVEAU_OX_15 = (int)AK.EVENTS.PLAY_NIVEAU_OX_15 ,
    NIVEAU_OX_25 = (int)AK.EVENTS.PLAY_NIVEAU_OX_25 ,
    NIVEAU_OX_50 = (int)AK.EVENTS.PLAY_NIVEAU_OX_50 ,
    NIVEAU_OX_75 = (int)AK.EVENTS.PLAY_NIVEAU_OX_75 ,
    PROTO_2_VOIX_004 = unchecked((int)AK.EVENTS.PLAY_PROTO_2_VOIX_004) ,
    PROTO_2_VOIX_005 = unchecked((int)AK.EVENTS.PLAY_PROTO_2_VOIX_005) ,
    PROTO_2_VOIX_006 = unchecked((int)AK.EVENTS.PLAY_PROTO_2_VOIX_006) ,
    PROTO_2_VOIX_007 = unchecked((int)AK.EVENTS.PLAY_PROTO_2_VOIX_007) ,
    PROTO_2_VOIX_008 = unchecked((int)AK.EVENTS.PLAY_PROTO_2_VOIX_008) ,
    PROTO_2_VOIX_009 = unchecked((int)AK.EVENTS.PLAY_PROTO_2_VOIX_009) ,
    PROTO_2_VOIX_010 = unchecked((int)AK.EVENTS.PLAY_PROTO_2_VOIX_010) ,
    PROTO_2_VOIX_011 = unchecked((int)AK.EVENTS.PLAY_PROTO_2_VOIX_011) ,
    PROTO_2_VOIX_012 = unchecked((int)AK.EVENTS.PLAY_PROTO_2_VOIX_012) ,
    PROTO_2_VOIX_AI_001= (int)AK.EVENTS.PLAY_PROTO_2_VOIX_AI_001,
    PROTO_2_VOIX_AI_002 = (int)AK.EVENTS.PLAY_PROTO_2_VOIX_AI_002 ,
    PROTO_2_VOIX_AI_003= (int)AK.EVENTS.PLAY_PROTO_2_VOIX_AI_003,
    RADIO_VOICE_START= (int)AK.EVENTS.PLAY_RADIO_VOICE_START,
    SFX_AMBIANCE_01 = (int)AK.EVENTS.PLAY_SFX_AMBIANCE_01 ,
    SFX_BUTTON_PRESS = (int)AK.EVENTS.PLAY_SFX_BUTTON_PRESS ,
    SFX_MONSTER_CALM_01 = unchecked((int)AK.EVENTS.PLAY_SFX_MONSTER_CALM_01) ,
    SFX_WATER_BREACH = unchecked((int)AK.EVENTS.PLAY_SFX_WATER_BREACH),
    SFX_WELDER_TAKE = (int)AK.EVENTS.PLAY_SFX_WELDER_TAKE ,
    SFX_WELDING= unchecked((int)AK.EVENTS.PLAY_SFX_WELDING),
    SFX_WELDING_AIR = unchecked((int)AK.EVENTS.PLAY_SFX_WELDING_AIR) ,
    STOP_RADIO_VOICE_START = (int)AK.EVENTS.STOP_RADIO_VOICE_START ,
    STOP_SFX_WATER_BREACH = (int)AK.EVENTS.STOP_SFX_WATER_BREACH ,
    STOP_SFX_WELDING = (int)AK.EVENTS.STOP_SFX_WELDING ,
    STOP_SFX_WELDING_AIR = (int)AK.EVENTS.STOP_SFX_WELDING_AIR
}
