using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public enum Wwise_ID_Enum_EVENTS
{
	PLAY_DEATH = unchecked((int)AK.EVENTS.PLAY_DEATH),
	PLAY_NIVEAU_OX_5 = unchecked((int)AK.EVENTS.PLAY_NIVEAU_OX_5),
	PLAY_NIVEAU_OX_10 = unchecked((int)AK.EVENTS.PLAY_NIVEAU_OX_10),
	PLAY_NIVEAU_OX_15 = unchecked((int)AK.EVENTS.PLAY_NIVEAU_OX_15),
	PLAY_NIVEAU_OX_25 = unchecked((int)AK.EVENTS.PLAY_NIVEAU_OX_25),
	PLAY_NIVEAU_OX_50 = unchecked((int)AK.EVENTS.PLAY_NIVEAU_OX_50),
	PLAY_NIVEAU_OX_75 = unchecked((int)AK.EVENTS.PLAY_NIVEAU_OX_75),
	PLAY_PROTO_2_VOIX_004 = unchecked((int)AK.EVENTS.PLAY_PROTO_2_VOIX_004),
	PLAY_PROTO_2_VOIX_005 = unchecked((int)AK.EVENTS.PLAY_PROTO_2_VOIX_005),
	PLAY_PROTO_2_VOIX_006 = unchecked((int)AK.EVENTS.PLAY_PROTO_2_VOIX_006),
	PLAY_PROTO_2_VOIX_007 = unchecked((int)AK.EVENTS.PLAY_PROTO_2_VOIX_007),
	PLAY_PROTO_2_VOIX_008 = unchecked((int)AK.EVENTS.PLAY_PROTO_2_VOIX_008),
	PLAY_PROTO_2_VOIX_009 = unchecked((int)AK.EVENTS.PLAY_PROTO_2_VOIX_009),
	PLAY_PROTO_2_VOIX_010 = unchecked((int)AK.EVENTS.PLAY_PROTO_2_VOIX_010),
	PLAY_PROTO_2_VOIX_011 = unchecked((int)AK.EVENTS.PLAY_PROTO_2_VOIX_011),
	PLAY_PROTO_2_VOIX_012 = unchecked((int)AK.EVENTS.PLAY_PROTO_2_VOIX_012),
	PLAY_PROTO_2_VOIX_AI_001 = unchecked((int)AK.EVENTS.PLAY_PROTO_2_VOIX_AI_001),
	PLAY_PROTO_2_VOIX_AI_002 = unchecked((int)AK.EVENTS.PLAY_PROTO_2_VOIX_AI_002),
	PLAY_PROTO_2_VOIX_AI_003 = unchecked((int)AK.EVENTS.PLAY_PROTO_2_VOIX_AI_003),
	PLAY_RADIO_VOICE_START = unchecked((int)AK.EVENTS.PLAY_RADIO_VOICE_START),
	PLAY_SFX_AMBIANCE_01 = unchecked((int)AK.EVENTS.PLAY_SFX_AMBIANCE_01),
	PLAY_SFX_BUTTON_PRESS = unchecked((int)AK.EVENTS.PLAY_SFX_BUTTON_PRESS),
	PLAY_SFX_BUTTON_TOUCH = unchecked((int)AK.EVENTS.PLAY_SFX_BUTTON_TOUCH),
	PLAY_SFX_MONSTER_AGGRESSIVE = unchecked((int)AK.EVENTS.PLAY_SFX_MONSTER_AGGRESSIVE),
	PLAY_SFX_MONSTER_ATTACK = unchecked((int)AK.EVENTS.PLAY_SFX_MONSTER_ATTACK),
	PLAY_SFX_MONSTER_CALM = unchecked((int)AK.EVENTS.PLAY_SFX_MONSTER_CALM),
	PLAY_SFX_RADAR = unchecked((int)AK.EVENTS.PLAY_SFX_RADAR),
	PLAY_SFX_WATER_BREACH = unchecked((int)AK.EVENTS.PLAY_SFX_WATER_BREACH),
	PLAY_SFX_WELDER_TAKE = unchecked((int)AK.EVENTS.PLAY_SFX_WELDER_TAKE),
	PLAY_SFX_WELDING = unchecked((int)AK.EVENTS.PLAY_SFX_WELDING),
	PLAY_SFX_WELDING_AIR = unchecked((int)AK.EVENTS.PLAY_SFX_WELDING_AIR),
	STOP_RADIO_VOICE_START = unchecked((int)AK.EVENTS.STOP_RADIO_VOICE_START),
	STOP_SFX_MONSTER_AGGRESSIVE = unchecked((int)AK.EVENTS.STOP_SFX_MONSTER_AGGRESSIVE),
	STOP_SFX_MONSTER_CALM = unchecked((int)AK.EVENTS.STOP_SFX_MONSTER_CALM),
	STOP_SFX_RADAR = unchecked((int)AK.EVENTS.STOP_SFX_RADAR),
	STOP_SFX_WATER_BREACH = unchecked((int)AK.EVENTS.STOP_SFX_WATER_BREACH),
	STOP_SFX_WELDING = unchecked((int)AK.EVENTS.STOP_SFX_WELDING),
	STOP_SFX_WELDING_AIR = unchecked((int)AK.EVENTS.STOP_SFX_WELDING_AIR),
}

public enum Wwise_ID_Enum_GAME_PARAMETERS
{
	RTPC_BREACH_SIZE = unchecked((int)AK.GAME_PARAMETERS.RTPC_BREACH_SIZE),
	RTPC_MUSIC_VOLUME = unchecked((int)AK.GAME_PARAMETERS.RTPC_MUSIC_VOLUME),
	RTPC_SFX_VOLUME = unchecked((int)AK.GAME_PARAMETERS.RTPC_SFX_VOLUME),
	RTPC_WELDER_AIR = unchecked((int)AK.GAME_PARAMETERS.RTPC_WELDER_AIR),
	SS_AIR_FEAR = unchecked((int)AK.GAME_PARAMETERS.SS_AIR_FEAR),
	SS_AIR_FREEFALL = unchecked((int)AK.GAME_PARAMETERS.SS_AIR_FREEFALL),
	SS_AIR_FURY = unchecked((int)AK.GAME_PARAMETERS.SS_AIR_FURY),
	SS_AIR_MONTH = unchecked((int)AK.GAME_PARAMETERS.SS_AIR_MONTH),
	SS_AIR_PRESENCE = unchecked((int)AK.GAME_PARAMETERS.SS_AIR_PRESENCE),
	SS_AIR_RPM = unchecked((int)AK.GAME_PARAMETERS.SS_AIR_RPM),
	SS_AIR_SIZE = unchecked((int)AK.GAME_PARAMETERS.SS_AIR_SIZE),
	SS_AIR_STORM = unchecked((int)AK.GAME_PARAMETERS.SS_AIR_STORM),
	SS_AIR_TIMEOFDAY = unchecked((int)AK.GAME_PARAMETERS.SS_AIR_TIMEOFDAY),
	SS_AIR_TURBULENCE = unchecked((int)AK.GAME_PARAMETERS.SS_AIR_TURBULENCE),
}

public enum Wwise_ID_Enum_BANKS
{
	INIT = unchecked((int)AK.BANKS.INIT),
	SE_MAIN_SOUNDBANK = unchecked((int)AK.BANKS.SE_MAIN_SOUNDBANK),
}

public enum Wwise_ID_Enum_BUSSES
{
	MAIN_5_1 = unchecked((int)AK.BUSSES.MAIN_5_1),
	MASTER_AUDIO_BUS = unchecked((int)AK.BUSSES.MASTER_AUDIO_BUS),
	MUSIC = unchecked((int)AK.BUSSES.MUSIC),
	SFX = unchecked((int)AK.BUSSES.SFX),
	VOICE = unchecked((int)AK.BUSSES.VOICE),
}

public enum Wwise_ID_Enum_AUX_BUSSES
{
	REVERB_MONSTER = unchecked((int)AK.AUX_BUSSES.REVERB_MONSTER),
	REVERB_SUBMARINE = unchecked((int)AK.AUX_BUSSES.REVERB_SUBMARINE),
}

public enum Wwise_ID_Enum_AUDIO_DEVICES
{
	COMMUNICATION = unchecked((int)AK.AUDIO_DEVICES.COMMUNICATION),
	NO_OUTPUT = unchecked((int)AK.AUDIO_DEVICES.NO_OUTPUT),
	SYSTEM = unchecked((int)AK.AUDIO_DEVICES.SYSTEM),
}
